name: Node.js CI/CD

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Creating NPM Release & Hosting on server
        uses: appleboy/ssh-action@master # An action made to control Linux servers
        with: # We set all our secrets here for the action, these won't be shown in the action logs
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/github-projects/simple-terminal-chat/
            git pull
            npm prune
            npm install
            docker build -t stc .
            docker run --restart unless-stopped -d -p 4500:4500 --name stc stc:latest
            npm publish