name: Node.js CI/CD

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Creating NPM Release & Hosting on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            whoami
            cd ~/github-projects/simple-terminal-chat/
            git checkout release
            git pull
            npm prune
            npm install
            docker build -t stc .
            docker rm -f stc || true
            docker run --restart unless-stopped -d -p 4500:3000 --name stc stc:latest
            npm publish